int a = 2 * 4;
int b = 5 % 3;
double c = 3.14 / 2.5;
boolean bool = true;
boolean bo = a > b;
boolean bo2 = 10 <= 25;
boolean bo3 = !bo;
5 + 4;
string s = "Hallo dies ist ein String äüö AÄÜÖ +_/% .;:???";
string s2 = s + " Concatenation";
double converted = toDouble("3.14");
string implicitConversion = 3.14;