/* Generated By:JavaCC: Do not edit this line. NawkParserConstants.java */
package interpreter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NawkParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AT = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int PPLUS = 3;
  /** RegularExpression Id. */
  int MINUS = 4;
  /** RegularExpression Id. */
  int MMINUS = 5;
  /** RegularExpression Id. */
  int STAR = 6;
  /** RegularExpression Id. */
  int SLASH = 7;
  /** RegularExpression Id. */
  int MOD = 8;
  /** RegularExpression Id. */
  int EXP = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int BANG = 11;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int LE = 15;
  /** RegularExpression Id. */
  int GE = 16;
  /** RegularExpression Id. */
  int NE = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int LPAREN = 20;
  /** RegularExpression Id. */
  int RPAREN = 21;
  /** RegularExpression Id. */
  int LBRACE = 22;
  /** RegularExpression Id. */
  int RBRACE = 23;
  /** RegularExpression Id. */
  int LBRACKET = 24;
  /** RegularExpression Id. */
  int RBRACKET = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int DOUBLE = 28;
  /** RegularExpression Id. */
  int INTEGER = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int BOOLEAN = 31;
  /** RegularExpression Id. */
  int CHAR = 32;
  /** RegularExpression Id. */
  int VOID = 33;
  /** RegularExpression Id. */
  int TRUE = 34;
  /** RegularExpression Id. */
  int FALSE = 35;
  /** RegularExpression Id. */
  int RETURN = 36;
  /** RegularExpression Id. */
  int DOT = 37;
  /** RegularExpression Id. */
  int DDOT = 38;
  /** RegularExpression Id. */
  int PRINT = 39;
  /** RegularExpression Id. */
  int WHILE = 40;
  /** RegularExpression Id. */
  int IF = 41;
  /** RegularExpression Id. */
  int ELSE = 42;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 43;
  /** RegularExpression Id. */
  int DOUBLE_LITERAL = 44;
  /** RegularExpression Id. */
  int CHAR_LTIERAL = 45;
  /** RegularExpression Id. */
  int STRING_LITERAL = 46;
  /** RegularExpression Id. */
  int Ident = 47;
  /** RegularExpression Id. */
  int anything = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"@\"",
    "\"+\"",
    "\"++\"",
    "\"-\"",
    "\"--\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"=\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"double\"",
    "\"int\"",
    "\"string\"",
    "\"boolean\"",
    "\"char\"",
    "\"void\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\".\"",
    "\":\"",
    "\"print\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "<INTEGER_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LTIERAL>",
    "<STRING_LITERAL>",
    "<Ident>",
    "\" \"",
    "\"\\t\"",
    "<anything>",
  };

}
